#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Estimate skeleton lengths from skeleton.ply outputs.

The script consumes an existing skeletonization output directory generated by
``skeletonize_pointcept_instances.py`` and computes one length per group plus
one length for the full skeleton. Lengths are estimated from ``skeleton.ply``
by:

1. building a local k-nearest-neighbor graph over the skeleton points,
2. splitting it into connected components,
3. reducing each component to a minimum spanning tree,
4. extracting the tree diameter path,
5. fitting a smooth 3D curve to that ordered path when possible, and
6. integrating the curve length.
"""

from __future__ import annotations

import argparse
import csv
import json
import math
import struct
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Sequence, Tuple

import numpy as np


@dataclass
class PlyHeader:
    format_name: str
    vertex_count: int
    vertex_properties: List[Tuple[str, str]]
    header_end_offset: int


@dataclass
class GraphComponentResult:
    component_index: int
    node_indices: List[int]
    raw_edge_count: int
    mst_edge_count: int
    had_cycle_before_cleanup: bool
    polyline_length: float
    curve_length: float
    path_indices: List[int]


PLY_TO_NUMPY = {
    "char": "i1",
    "uchar": "u1",
    "short": "<i2",
    "ushort": "<u2",
    "int": "<i4",
    "uint": "<u4",
    "float": "<f4",
    "double": "<f8",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Compute curve-based lengths from skeleton.ply outputs."
    )
    parser.add_argument(
        "--skeleton-root",
        type=Path,
        required=True,
        help="Root directory produced by skeletonize_pointcept_instances.py.",
    )
    parser.add_argument(
        "--output-json",
        type=Path,
        default=None,
        help="Optional JSON output path. Defaults to <skeleton-root>/curve_length_summary.json",
    )
    parser.add_argument(
        "--output-csv",
        type=Path,
        default=None,
        help="Optional CSV output path. Defaults to <skeleton-root>/curve_length_summary.csv",
    )
    parser.add_argument(
        "--k-neighbors",
        type=int,
        default=4,
        help="Number of nearest neighbors used to build the local skeleton graph.",
    )
    parser.add_argument(
        "--resample-points",
        type=int,
        default=200,
        help="Number of samples used to integrate spline arc length.",
    )
    parser.add_argument(
        "--spline-smoothing",
        type=float,
        default=1e-4,
        help="Conservative smoothing factor for spline fitting.",
    )
    parser.add_argument(
        "--include-full",
        action="store_true",
        default=True,
        help="Also compute length for the full skeleton.",
    )
    return parser.parse_args()


def parse_ply_header(file_obj) -> PlyHeader:
    format_name = None
    vertex_count = None
    vertex_properties: List[Tuple[str, str]] = []
    in_vertex_element = False

    while True:
        line = file_obj.readline()
        if not line:
            raise ValueError("Unexpected EOF while reading PLY header.")
        decoded = line.decode("utf-8", errors="ignore").strip()
        if decoded == "ply":
            continue
        if decoded.startswith("format "):
            parts = decoded.split()
            if len(parts) < 2:
                raise ValueError(f"Malformed PLY format line: {decoded}")
            format_name = parts[1]
        elif decoded.startswith("element "):
            parts = decoded.split()
            if len(parts) >= 3 and parts[1] == "vertex":
                vertex_count = int(parts[2])
                vertex_properties = []
                in_vertex_element = True
            else:
                in_vertex_element = False
        elif decoded.startswith("property ") and in_vertex_element:
            parts = decoded.split()
            if len(parts) == 3:
                vertex_properties.append((parts[1], parts[2]))
            else:
                raise ValueError(f"Unsupported vertex property declaration: {decoded}")
        elif decoded == "end_header":
            break

    if format_name is None or vertex_count is None:
        raise ValueError("PLY header is missing format or vertex count.")

    return PlyHeader(
        format_name=format_name,
        vertex_count=vertex_count,
        vertex_properties=vertex_properties,
        header_end_offset=file_obj.tell(),
    )


def read_ply_points(file_path: Path) -> np.ndarray:
    with file_path.open("rb") as f:
        header = parse_ply_header(f)
        property_names = [name for _, name in header.vertex_properties]
        if "x" not in property_names or "y" not in property_names or "z" not in property_names:
            raise ValueError(f"PLY is missing x/y/z properties: {file_path}")

        if header.format_name == "ascii":
            points = np.empty((header.vertex_count, 3), dtype=np.float64)
            for idx in range(header.vertex_count):
                line = f.readline()
                if not line:
                    raise ValueError("Unexpected EOF in ASCII PLY vertex section.")
                parts = line.decode("utf-8", errors="ignore").strip().split()
                if len(parts) < len(property_names):
                    raise ValueError(
                        f"Vertex line has {len(parts)} values, expected at least {len(property_names)}."
                    )
                name_to_value = {
                    property_names[prop_idx]: float(parts[prop_idx]) for prop_idx in range(len(property_names))
                }
                points[idx] = [name_to_value["x"], name_to_value["y"], name_to_value["z"]]
            return points

        if header.format_name != "binary_little_endian":
            raise ValueError(
                f"Unsupported PLY format '{header.format_name}'. Only ascii and binary_little_endian are supported."
            )

        dtype_fields = []
        for prop_type, prop_name in header.vertex_properties:
            if prop_type not in PLY_TO_NUMPY:
                raise ValueError(f"Unsupported PLY property type '{prop_type}' in {file_path}")
            dtype_fields.append((prop_name, PLY_TO_NUMPY[prop_type]))
        dtype = np.dtype(dtype_fields)
        data = np.fromfile(f, dtype=dtype, count=header.vertex_count)
        return np.column_stack([data["x"], data["y"], data["z"]]).astype(np.float64, copy=False)


def pairwise_knn(points: np.ndarray, k_neighbors: int) -> np.ndarray:
    if points.shape[0] <= 1:
        return np.zeros((points.shape[0], 0), dtype=np.int64)

    max_k = min(max(k_neighbors, 1), points.shape[0] - 1)
    try:
        from scipy.spatial import cKDTree  # type: ignore

        tree = cKDTree(points)
        _, indices = tree.query(points, k=max_k + 1)
        indices = np.asarray(indices)
        if indices.ndim == 1:
            indices = indices[:, None]
        return indices[:, 1:]
    except Exception:
        diff = points[:, None, :] - points[None, :, :]
        dist = np.linalg.norm(diff, axis=2)
        np.fill_diagonal(dist, np.inf)
        order = np.argsort(dist, axis=1)
        return order[:, :max_k]


def build_knn_edges(points: np.ndarray, k_neighbors: int) -> List[Tuple[int, int, float]]:
    if points.shape[0] <= 1:
        return []

    neighbor_indices = pairwise_knn(points, k_neighbors)
    edge_map: Dict[Tuple[int, int], float] = {}
    for src_idx in range(points.shape[0]):
        for dst_idx in neighbor_indices[src_idx]:
            dst_idx = int(dst_idx)
            if src_idx == dst_idx:
                continue
            u, v = sorted((src_idx, dst_idx))
            weight = float(np.linalg.norm(points[u] - points[v]))
            key = (u, v)
            current = edge_map.get(key)
            if current is None or weight < current:
                edge_map[key] = weight
    return [(u, v, w) for (u, v), w in sorted(edge_map.items())]


class UnionFind:
    def __init__(self, nodes: Iterable[int]):
        self.parent = {node: node for node in nodes}
        self.rank = {node: 0 for node in nodes}

    def find(self, node: int) -> int:
        parent = self.parent[node]
        if parent != node:
            self.parent[node] = self.find(parent)
        return self.parent[node]

    def union(self, a: int, b: int) -> bool:
        root_a = self.find(a)
        root_b = self.find(b)
        if root_a == root_b:
            return False
        rank_a = self.rank[root_a]
        rank_b = self.rank[root_b]
        if rank_a < rank_b:
            self.parent[root_a] = root_b
        elif rank_a > rank_b:
            self.parent[root_b] = root_a
        else:
            self.parent[root_b] = root_a
            self.rank[root_a] += 1
        return True


def connected_components(node_count: int, edges: Sequence[Tuple[int, int, float]]) -> List[List[int]]:
    adjacency = [[] for _ in range(node_count)]
    for u, v, _ in edges:
        adjacency[u].append(v)
        adjacency[v].append(u)

    visited = [False] * node_count
    components: List[List[int]] = []
    for node in range(node_count):
        if visited[node]:
            continue
        stack = [node]
        visited[node] = True
        component = []
        while stack:
            current = stack.pop()
            component.append(current)
            for neighbor in adjacency[current]:
                if not visited[neighbor]:
                    visited[neighbor] = True
                    stack.append(neighbor)
        components.append(sorted(component))
    return components


def minimum_spanning_tree(
    node_indices: Sequence[int], edges: Sequence[Tuple[int, int, float]]
) -> List[Tuple[int, int, float]]:
    if len(node_indices) <= 1:
        return []
    node_set = set(node_indices)
    filtered = [edge for edge in edges if edge[0] in node_set and edge[1] in node_set]
    filtered.sort(key=lambda item: item[2])
    uf = UnionFind(node_indices)
    mst_edges: List[Tuple[int, int, float]] = []
    for u, v, weight in filtered:
        if uf.union(u, v):
            mst_edges.append((u, v, weight))
            if len(mst_edges) == len(node_indices) - 1:
                break
    return mst_edges


def build_adjacency(
    node_count: int, edges: Sequence[Tuple[int, int, float]]
) -> List[List[Tuple[int, float]]]:
    adjacency: List[List[Tuple[int, float]]] = [[] for _ in range(node_count)]
    for u, v, weight in edges:
        adjacency[u].append((v, weight))
        adjacency[v].append((u, weight))
    return adjacency


def farthest_node(
    start_node: int, adjacency: Sequence[Sequence[Tuple[int, float]]], allowed_nodes: set[int]
) -> Tuple[int, float, Dict[int, int]]:
    stack = [(start_node, -1, 0.0)]
    farthest = start_node
    max_dist = 0.0
    parent: Dict[int, int] = {start_node: -1}
    visited = set()

    while stack:
        node, par, acc = stack.pop()
        if node in visited:
            continue
        visited.add(node)
        parent[node] = par
        if acc > max_dist:
            farthest = node
            max_dist = acc
        for neighbor, weight in adjacency[node]:
            if neighbor not in allowed_nodes or neighbor == par:
                continue
            stack.append((neighbor, node, acc + weight))
    return farthest, max_dist, parent


def tree_diameter_path(
    node_indices: Sequence[int], mst_edges: Sequence[Tuple[int, int, float]], node_count: int
) -> Tuple[List[int], float]:
    if not node_indices:
        return [], 0.0
    if len(node_indices) == 1:
        return [int(node_indices[0])], 0.0

    allowed_nodes = set(int(node) for node in node_indices)
    adjacency = build_adjacency(node_count, mst_edges)
    start = int(node_indices[0])
    endpoint_a, _, _ = farthest_node(start, adjacency, allowed_nodes)
    endpoint_b, max_dist, parent = farthest_node(endpoint_a, adjacency, allowed_nodes)

    path = [endpoint_b]
    current = endpoint_b
    while current != endpoint_a:
        current = parent[current]
        if current == -1:
            raise RuntimeError("Failed to reconstruct diameter path from MST.")
        path.append(current)
    path.reverse()
    return path, max_dist


def polyline_length(points: np.ndarray) -> float:
    if points.shape[0] <= 1:
        return 0.0
    return float(np.linalg.norm(np.diff(points, axis=0), axis=1).sum())


def spline_curve_length(
    ordered_points: np.ndarray, resample_points: int, spline_smoothing: float
) -> float:
    if ordered_points.shape[0] <= 1:
        return 0.0
    if ordered_points.shape[0] == 2:
        return float(np.linalg.norm(ordered_points[1] - ordered_points[0]))

    base_length = polyline_length(ordered_points)
    if ordered_points.shape[0] < 4:
        return base_length

    chord = np.linalg.norm(np.diff(ordered_points, axis=0), axis=1)
    if np.allclose(chord.sum(), 0.0):
        return 0.0
    u = np.concatenate(([0.0], np.cumsum(chord)))
    u /= u[-1]

    try:
        from scipy.interpolate import splev, splprep  # type: ignore

        spline_degree = min(3, ordered_points.shape[0] - 1)
        tck, _ = splprep(
            ordered_points.T,
            u=u,
            s=float(spline_smoothing),
            k=spline_degree,
        )
        sample_u = np.linspace(0.0, 1.0, max(int(resample_points), 2))
        sampled = np.asarray(splev(sample_u, tck)).T
        return polyline_length(sampled)
    except Exception:
        return base_length


def compute_component_curve_length(
    points: np.ndarray,
    node_indices: Sequence[int],
    component_edges: Sequence[Tuple[int, int, float]],
    node_count: int,
    component_index: int,
    resample_points: int,
    spline_smoothing: float,
) -> GraphComponentResult:
    if len(node_indices) == 1:
        only_node = int(node_indices[0])
        return GraphComponentResult(
            component_index=component_index,
            node_indices=[only_node],
            raw_edge_count=0,
            mst_edge_count=0,
            had_cycle_before_cleanup=False,
            polyline_length=0.0,
            curve_length=0.0,
            path_indices=[only_node],
        )

    mst_edges = minimum_spanning_tree(node_indices, component_edges)
    had_cycle = len(component_edges) > max(len(node_indices) - 1, 0)
    path_indices, _ = tree_diameter_path(node_indices, mst_edges, node_count=node_count)
    path_points = points[np.asarray(path_indices, dtype=np.int64)]
    line_length = polyline_length(path_points)
    curve_length = spline_curve_length(
        path_points, resample_points=resample_points, spline_smoothing=spline_smoothing
    )
    return GraphComponentResult(
        component_index=component_index,
        node_indices=[int(node) for node in node_indices],
        raw_edge_count=len(component_edges),
        mst_edge_count=len(mst_edges),
        had_cycle_before_cleanup=had_cycle,
        polyline_length=line_length,
        curve_length=curve_length,
        path_indices=[int(node) for node in path_indices],
    )


def analyze_skeleton_points(
    points: np.ndarray,
    k_neighbors: int,
    resample_points: int,
    spline_smoothing: float,
) -> Dict[str, object]:
    if points.shape[0] == 0:
        return {
            "num_skeleton_points": 0,
            "component_count": 0,
            "component_lengths": [],
            "component_polyline_lengths": [],
            "largest_component_length": 0.0,
            "curve_length_sum": 0.0,
            "polyline_length_sum": 0.0,
            "had_cycle_before_cleanup": False,
            "component_details": [],
        }

    edges = build_knn_edges(points, k_neighbors=k_neighbors)
    components = connected_components(points.shape[0], edges)
    component_results: List[GraphComponentResult] = []
    for component_index, node_indices in enumerate(components):
        node_set = set(node_indices)
        component_edges = [
            edge for edge in edges if edge[0] in node_set and edge[1] in node_set
        ]
        component_results.append(
            compute_component_curve_length(
                points=points,
                node_indices=node_indices,
                component_edges=component_edges,
                node_count=points.shape[0],
                component_index=component_index,
                resample_points=resample_points,
                spline_smoothing=spline_smoothing,
            )
        )

    curve_lengths = [result.curve_length for result in component_results]
    polyline_lengths = [result.polyline_length for result in component_results]
    return {
        "num_skeleton_points": int(points.shape[0]),
        "component_count": len(component_results),
        "component_lengths": curve_lengths,
        "component_polyline_lengths": polyline_lengths,
        "largest_component_length": float(max(curve_lengths) if curve_lengths else 0.0),
        "curve_length_sum": float(sum(curve_lengths)),
        "polyline_length_sum": float(sum(polyline_lengths)),
        "had_cycle_before_cleanup": bool(
            any(result.had_cycle_before_cleanup for result in component_results)
        ),
        "component_details": [
            {
                "component_index": result.component_index,
                "node_count": len(result.node_indices),
                "raw_edge_count": result.raw_edge_count,
                "mst_edge_count": result.mst_edge_count,
                "had_cycle_before_cleanup": result.had_cycle_before_cleanup,
                "polyline_length": result.polyline_length,
                "curve_length": result.curve_length,
                "path_node_count": len(result.path_indices),
            }
            for result in component_results
        ],
    }


def analyze_entry(
    entry: Dict[str, object],
    scope: str,
    skeleton_ply: Optional[Path],
    k_neighbors: int,
    resample_points: int,
    spline_smoothing: float,
) -> Dict[str, object]:
    result = {
        "scope": scope,
        "name": entry.get("name", scope),
        "label": entry.get("label"),
        "status": "pending",
        "source_skeleton_ply": str(skeleton_ply.resolve()) if skeleton_ply else None,
    }

    if entry.get("status") != "ok" or skeleton_ply is None or not skeleton_ply.exists():
        result["status"] = "missing_or_failed"
        result["reason"] = entry.get("reason", "source skeleton is missing or original skeletonization failed")
        return result

    try:
        points = read_ply_points(skeleton_ply)
        metrics = analyze_skeleton_points(
            points,
            k_neighbors=k_neighbors,
            resample_points=resample_points,
            spline_smoothing=spline_smoothing,
        )
        result.update(metrics)
        result["status"] = "ok"
    except Exception as exc:
        result["status"] = "analysis_failed"
        result["reason"] = str(exc)
    return result


def default_output_path(skeleton_root: Path, filename: str, override: Optional[Path]) -> Path:
    return override.resolve() if override is not None else (skeleton_root / filename).resolve()


def csv_rows_from_results(group_results: Sequence[Dict[str, object]], full_result: Optional[Dict[str, object]]) -> List[Dict[str, object]]:
    rows = []
    if full_result is not None:
        rows.append(full_result)
    rows.extend(group_results)
    normalized_rows = []
    for row in rows:
        normalized_rows.append(
            {
                "scope": row.get("scope"),
                "name": row.get("name"),
                "label": row.get("label"),
                "status": row.get("status"),
                "curve_length_sum": row.get("curve_length_sum"),
                "polyline_length_sum": row.get("polyline_length_sum"),
                "largest_component_length": row.get("largest_component_length"),
                "component_count": row.get("component_count"),
                "num_skeleton_points": row.get("num_skeleton_points"),
                "had_cycle_before_cleanup": row.get("had_cycle_before_cleanup"),
                "source_skeleton_ply": row.get("source_skeleton_ply"),
                "reason": row.get("reason"),
                "component_lengths": json.dumps(row.get("component_lengths"), ensure_ascii=False),
            }
        )
    return normalized_rows


def write_csv(path: Path, rows: Sequence[Dict[str, object]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fieldnames = [
        "scope",
        "name",
        "label",
        "status",
        "curve_length_sum",
        "polyline_length_sum",
        "largest_component_length",
        "component_count",
        "num_skeleton_points",
        "had_cycle_before_cleanup",
        "source_skeleton_ply",
        "reason",
        "component_lengths",
    ]
    with path.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        for row in rows:
            writer.writerow(row)


def main() -> int:
    args = parse_args()
    skeleton_root = args.skeleton_root.resolve()
    summary_path = skeleton_root / "summary.json"
    if not summary_path.exists():
        raise FileNotFoundError(f"summary.json not found under skeleton root: {summary_path}")

    summary = json.loads(summary_path.read_text(encoding="utf-8"))
    group_entries = summary.get("groups", [])
    if not isinstance(group_entries, list):
        raise ValueError("summary.json does not contain a valid 'groups' list.")

    group_results = []
    for entry in group_entries:
        output_dir = entry.get("output_dir")
        skeleton_ply = Path(output_dir) / "skeleton.ply" if output_dir else None
        group_results.append(
            analyze_entry(
                entry=entry,
                scope="group",
                skeleton_ply=skeleton_ply,
                k_neighbors=args.k_neighbors,
                resample_points=args.resample_points,
                spline_smoothing=args.spline_smoothing,
            )
        )

    full_result = None
    if args.include_full and isinstance(summary.get("full"), dict):
        full_entry = dict(summary["full"])
        full_entry["name"] = "full"
        full_output_dir = full_entry.get("output_dir")
        full_ply = Path(full_output_dir) / "skeleton.ply" if full_output_dir else None
        full_result = analyze_entry(
            entry=full_entry,
            scope="full",
            skeleton_ply=full_ply,
            k_neighbors=args.k_neighbors,
            resample_points=args.resample_points,
            spline_smoothing=args.spline_smoothing,
        )

    output_json = default_output_path(
        skeleton_root, "curve_length_summary.json", args.output_json
    )
    output_csv = default_output_path(
        skeleton_root, "curve_length_summary.csv", args.output_csv
    )

    payload = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "skeleton_root": str(skeleton_root),
        "summary_json": str(summary_path.resolve()),
        "k_neighbors": int(args.k_neighbors),
        "resample_points": int(args.resample_points),
        "spline_smoothing": float(args.spline_smoothing),
        "full": full_result,
        "groups": group_results,
        "num_groups_total": len(group_results),
        "num_groups_ok": sum(item.get("status") == "ok" for item in group_results),
        "num_groups_missing_or_failed": sum(
            item.get("status") != "ok" for item in group_results
        ),
    }
    output_json.parent.mkdir(parents=True, exist_ok=True)
    output_json.write_text(json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8")
    write_csv(output_csv, csv_rows_from_results(group_results, full_result))

    print(f"[INFO] Wrote JSON summary to {output_json}")
    print(f"[INFO] Wrote CSV summary to {output_csv}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
